easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
        - App\Entity\User
        - App\Entity\Blog
    design:
        brand_color: '#1ABC9C'          

    site_name: '<img src="http://symfony.com/logos/symfony_white_01.png" />'