vich_uploader:
    db_driver: orm

    mappings:
        doc:
            uri_prefix: /images/doc
            upload_destination: '%kernel.project_dir%/public/images/doc'
            namer: vich_uploader.namer_origname
     